### ISSUE TITLE
E2E test not running correctly

### ISSUE THREAD

**Issue by ayoub-tl** [onosproject/sdran-in-a-box#172]
Hello
after installing sdran with no error messages and having deployed  all the pods, the E2E test are not working, can someone help please
After a while the test no longor work

![image](https://user-images.githubusercontent.com/68382823/161423236-c9d16b7d-82be-48bf-8c1d-37dbbc2a4e3a.png)
![image](https://user-images.githubusercontent.com/68382823/161423282-615bd486-ed8a-4c57-9f8d-f6398c16f467.png)

**Comment by natanzi** [comment]
What was the issue?
