### ISSUE TITLE
Error deploying ransim

### ISSUE THREAD

**Issue by ahassaneinn** [onosproject/sdran-in-a-box#173]
Hello, I was trying to deploy raib OPT=ransim VER=latest and I keep running into this error

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.securityContext): unknown field "seccompProfile" in io.k8s.api.core.v1.PodSecurityContext
mk/[ric.mk:10](http://ric.mk:10/): recipe for target '/home/elliot/sdran-in-a-box//workspace/milestones/ric' failed
make: *** [/home/elliot/sdran-in-a-box//workspace/milestones/ric] Error 1

![Error](https://user-images.githubusercontent.com/103948640/163831031-b3514f77-9f5c-48be-8cb6-c000e5f7f353.png)

When I scrolled through the terminal I also noticed the following error

![image](https://user-images.githubusercontent.com/103948640/163831365-f923fa2b-e5bb-4add-8abc-4eb967b8dd1d.png)

I tried a different things to fix the situation but I could not resolve it. Do you have any idea how I can get it to work? Thanks.

**Comment by MyNoriJun** [comment]
Execuse me, I have the same problem. I want to know whether you fixed it. I found no sd-ran in the sd-ran directory.
