### ISSUE TITLE
Receive Error 1

### ISSUE THREAD

**Issue by natanzi** [onosproject/sdran-in-a-box#180]
Does anybody know the origin of the below issue during the installation?
sdran-in-a-box//workspace/milestones/k8s-ready] Error 1
....
pod/onos-operator-topo-5f8cd6ff7c-xp6pz condition met
timed out waiting for the condition on pods/atomix-controller-99f978c7d-ltrc6
timed out waiting for the condition on pods/coredns-dff8fc7d-psx5k
timed out waiting for the condition on pods/kubernetes-dashboard-667c4c65f8-ffgvw
timed out waiting for the condition on pods/onos-operator-app-588d479876-cm8gg
mk/infra.mk:29: recipe for target '/home/milad/sdran-in-a-box//workspace/milestones/k8s-ready' failed
make: *** [/home/milad/sdran-in-a-box//workspace/milestones/k8s-ready] Error 1

**Comment by eclipse95** [comment]
Hi,
I had the same problem. I solved it by setting DNS in systemd-resolved (file `/etc/systemd/resolved.conf`) and restarting the service `systemd-resolved`.
During the installation of k8s by kubespray, it replaces the DNS setting and looses the original configuration. During the downloading of the pods, there is no DNS resolution so it can't download.

**Comment by woojoong88** [comment]
I think issue is solved. Going to close the issue.
