### ISSUE TITLE
go: unknown subcommand "mod"

### ISSUE THREAD

**Issue by natanzi** [onosproject/sdran-in-a-box#182]
After running go mode tidy (for example)
I have received the below error:

go: unknown subcommand "mod"
Run 'go help' for usage.

Why is this the case?

**Comment by natanzi** [comment]
Reason:
Go 1.10 knows no mod subcommand, the go version should be updated to 1.11
preferably the newest 1.14 version of Go

**Comment by woojoong88** [comment]
I don't think this is RiaB issue. I am not sure where `go mod` is necessary on RiaB. Since it is out of scope, I will close this issue.
